apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: n8n-claim0
  name: n8n-claim0
  namespace: n8n
spec:
  storageClassName: nfs-client-storage-1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
