name: Kubelinter on Dev Branch

on:
  push:
    branches:
      - main

jobs:
  kubelinter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Kubelinter
        run: |
          curl -Lo kubelinter.tar.gz https://github.com/stackrox/kube-linter/releases/latest/download/kube-linter-linux.tar.gz
          tar -xzf kubelinter.tar.gz
          chmod +x kube-linter
          sudo mv kube-linter /usr/local/bin/

      - name: Lint YAML files and Generate Report
        continue-on-error: true
        run: |
          kubelinter lint -o checkstyle > kubelinter-report.txt


      - name: Upload Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: kubelinter-report
          path: kubelinter-report.txt