name: Kubelinter on Dev Branch

on:
  push:
    branches:
      - main

jobs:
  kubelinter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Kubelinter
        run: |
          curl -Lo kubelinter.tar.gz https://github.com/stackrox/kube-linter/releases/latest/download/kube-linter-linux.tar.gz
          tar -xzf kubelinter.tar.gz
          chmod +x kube-linter
          sudo mv kube-linter /usr/local/bin/

      - name: Lint YAML files in the repository
        continue-on-error: true
        run: kube-linter lint . > kube-linter-report.txt

      - name: Upload report as sarif
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: kube-linter-report.txt

      - name: Fail if the kube-linter report contains lines
        run: |
          if grep -q . kube-linter-report.txt; then
            echo "kube-linter found issues in the repository"
            exit 1
          fi