name: Kubelinter on Dev Branch

on:
  push:
    branches:
      - main

jobs:
  kubelinter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Scan repo with kube-linter
        continue-on-error: true
        uses: stackrox/kube-linter-action@v1.0.4
        with:
          directory: .
          format: sarif
          output-file: kube-linter-results.sarif

      - name: Cat results
        run: cat kube-linter-results.sarif

      - name: Upload SARIF results to GitHub
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: kube-linter-results.sarif
          category: 'KubeLinter'
